### ISSUE TITLE
List access point fails in case there's an AP w/o POSIX user

### ISSUE THREAD

**Issue by yaronya** [kubernetes-sigs/aws-efs-csi-driver#1164]
/kind bug

**What happened?**
I had an AP created manually under the EFS configured for the CSI driver. The AP did not have a Posix User configured.
After I upgraded to 2.5.0 - I saw that the controller is stuck in crash loop.

**What you expected to happen?**
Skip the AP, or at least print an error/warning without panic.

**How to reproduce it (as minimally and precisely as possible)?**
1. Create an AP without Posix User configured for a given EFS
2. Configure a `StorageClass` to use the `fileSystemId` of that EFS
3. Controller pod enters a crash loop, logs will yield the below panic log.

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.28.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.12-eks-2d98532
```
- Driver version: 2.5.0

**Please also attach debug logs to help us better diagnose**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16220e6]

goroutine 101 [running]:
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud.(*cloud).ListAccessPoints(0xc000168380, {0x1e5e9b0, 0xc0008048d0}, {0xc00013ec20, 0xb})
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/cloud/cloud.go:317 +0x2e6
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getUsedGids(0x6acfc0?, {0x1e5e9b0?, 0xc0008048d0?}, {0xc00013ec20, 0xb})
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:66 +0x53
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).getNextGid(0xc0006163d8, {0x1e5e9b0, 0xc0008048d0}, {0xc00013ec20, 0xb}, 0x1e708d0?, 0x19cf700?)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:42 +0x1fe
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).CreateVolume(0xc000616340, {0x1e5e9b0, 0xc0008048d0}, 0xc0007dd730)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/controller.go:257 +0x14fe
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x1e5e9b0, 0xc0008048d0}, {0x19cb100?, 0xc0007dd730})
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x78
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).Run.func1({0x1e5e9b0?, 0xc0008048d0?}, {0x19cb100?, 0xc0007dd730?}, 0xc000577a50?, 0x1861ee0?)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/driver.go:101 +0x42
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x1a31640?, 0xc000616340}, {0x1e5e9b0, 0xc0008048d0}, 0xc0007dd6c0, 0x1b7c558)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5680 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001be000, {0x1e644e0, 0xc0006829c0}, 0xc00024cb40, 0xc000519a10, 0x2aecc40, 0x0)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0001be000, {0x1e644e0, 0xc0006829c0}, 0xc00024cb40, 0x0)
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:963 +0x28a

```

- Instructions to gather debug logs can be found [here](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/master/troubleshooting)

**Comment by mskanth972** [comment]
Hi @yaronya, thanks for bringing here. We will investigate this on priority.

**Comment by mskanth972** [comment]
I added https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/1180 which can solve this issue and we will merge this soon and mark in the next release.

**Comment by mskanth972** [comment]
Closing this issue as the latest release v1.7.1 has fixed it. Feel free to open if you are facing the issue still.
/close
