### ISSUE TITLE
Please tag a new version

### ISSUE THREAD

**Issue by 2uasimojo** [kubernetes-sigs/aws-efs-csi-driver#152]
/kind bug

Requesting a new tagged image (`release-0.4`) built against an `efs-utils` >= 1.23.

We will use `latest` for the time being, but would like to be able to use a "frozen" version as soon as feasible. Thanks in advance!

**What happened?**
When I try to use the `tls` `mountOption` the `mount` command fails with

```
  Warning  FailedMount  27s (x7 over 61s)  kubelet, ip-10-0-130-137.us-west-1.compute.internal  MountVolume.SetUp failed for volume "efs-pv" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "fs-c3b5e0da:/" at "/var/lib/kubelet/pods/96f1ea12-4d2b-400c-85c8-72853cb8ef17/volumes/kubernetes.io~csi/efs-pv/mount": mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t efs -o tls,accesspoint=fsap-01b2c12c8578dceff fs-c3b5e0da:/ /var/lib/kubelet/pods/96f1ea12-4d2b-400c-85c8-72853cb8ef17/volumes/kubernetes.io~csi/efs-pv/mount
Output: Traceback (most recent call last):
  File "/sbin/mount.efs", line 1375, in <module>
    main()
  File "/sbin/mount.efs", line 1369, in main
    mount_tls(config, init_system, dns_name, path, fs_id, mountpoint, options)
  File "/sbin/mount.efs", line 1302, in mount_tls
    with bootstrap_tls(config, init_system, dns_name, fs_id, mountpoint, options) as tunnel_proc:
  File "/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/sbin/mount.efs", line 705, in bootstrap_tls
    security_credentials, ap_id=ap_id, base_path=state_file_dir)
  File "/sbin/mount.efs", line 848, in create_certificate
    private_key = check_and_create_private_key(base_path)
  File "/sbin/mount.efs", line 911, in check_and_create_private_key
    do_with_lock(generate_key)
  File "/sbin/mount.efs", line 894, in do_with_lock
    return function()
  File "/sbin/mount.efs", line 907, in generate_key
    subprocess_call(cmd, 'Failed to create private key')
  File "/sbin/mount.efs", line 970, in subprocess_call
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
  File "/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**What you expected to happen?**
Mount works, my pod starts up, and I use it to save the world.

**How to reproduce it (as minimally and precisely as possible)?**
Using [this daemonset](https://github.com/openshift/managed-cluster-config/blob/4f6fca8a086050201d6ff4160de9cdd4fb2ccb26/deploy/efs-csi/04-daemonset.yaml) and a PersistentVolume with access points and TLS like this:

```yaml
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv-ap
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  mountOptions:
  - tls
  # File system access point ID
  - accesspoint=fsap-00921f3d0a7d73a6e
  csi:
    driver: efs.csi.aws.com
    # EFS volume ID
    volumeHandle: fs-c29e7341
```

**Anything else we need to know?**:
Debugged this and found it's coming from `efs-utils` when it tries to use `openssl` to create a key. The `ENOENT` is because the `openssl` binary doesn't exist. The `openssl` binary doesn't exist because `release-0.3` was built with `amazon-efs-utils 1.21`. The dependency on `openssl` wasn't added until `1.23` (in [this commit](https://github.com/aws/efs-utils/commit/47506a753747524fa4c70552360202a03afc8e25)).

**Environment**
- Kubernetes version (use `kubectl version`):
```bash
$ oc version
Client Version: openshift-clients-4.3-31-gc25fb9c7
Server Version: 4.3.12
Kubernetes Version: v1.16.2
```
- Driver version:
At tag `release-0.3`

**Comment by 2uasimojo** [comment]
> /kind bug

I don't think this is a bug, btw, but I'm not sure what it is.

**Comment by jharrington22** [comment]
I am able to replicate this issue with `v0.3.0` 

```
oc get pods -n openshift-efs-csi efs-csi-node-5qjcs -o json | jq 
-r '.spec.containers[].image'
registry.hub.docker.com/amazon/aws-efs-csi-driver:v0.3.0
quay.io/k8scsi/csi-node-driver-registrar:v1.1.0
quay.io/k8scsi/livenessprobe:v1.1.0
```

```
  Type     Reason       Age                 From                                   Message
  ----     ------       ----                ----                                   -------
  Normal   Scheduled    <unknown>           default-scheduler                      Successfully assigned efs-csi/test-efs to ip-10-0-133-140.ec2.internal
  Warning  FailedMount  40s (x8 over 108s)  kubelet, ip-10-0-133-140.ec2.internal  MountVolume.SetUp failed for volume "efs-pv" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "fs-72f418f1:/" at "/var/lib/kubelet/pods/1ab8acad-ef64-4a58-87ea-70941a4d3be5/volumes/kubernetes.io~csi/efs-pv/mount": mount failed: exit status 1
Mounting command: mount
Mounting arguments: -t efs -o tls,accesspoint=fsap-0daaae2ae7ca80dca fs-72f418f1:/ /var/lib/kubelet/pods/1ab8acad-ef64-4a58-87ea-70941a4d3be5/volumes/kubernetes.io~csi/efs-pv/mount
Output: Traceback (most recent call last):
  File "/sbin/mount.efs", line 1375, in <module>
    main()
  File "/sbin/mount.efs", line 1369, in main
    mount_tls(config, init_system, dns_name, path, fs_id, mountpoint, options)
  File "/sbin/mount.efs", line 1302, in mount_tls
    with bootstrap_tls(config, init_system, dns_name, fs_id, mountpoint, options) as tunnel_proc:
  File "/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/sbin/mount.efs", line 705, in bootstrap_tls
    security_credentials, ap_id=ap_id, base_path=state_file_dir)
  File "/sbin/mount.efs", line 848, in create_certificate
    private_key = check_and_create_private_key(base_path)
  File "/sbin/mount.efs", line 911, in check_and_create_private_key
    do_with_lock(generate_key)
  File "/sbin/mount.efs", line 894, in do_with_lock
    return function()
  File "/sbin/mount.efs", line 907, in generate_key
    subprocess_call(cmd, 'Failed to create private key')
  File "/sbin/mount.efs", line 970, in subprocess_call
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE, stderr=subprocess.PIPE, close_fds=True)
  File "/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by farshad-hobsons** [comment]
I encountered an issue similar to https://github.com/kubernetes-sigs/aws-efs-csi-driver/issues/141 while on the branch `release-0.3` but master(commit-id: ad02e03877144f120e45f611d873b8688dee3e35) worked fine for me. 

So I am also requesting for a new tagged release.

**Comment by ossareh** [comment]
Literally just burned with this; I've been using `:latest` for some time (approx. 4 weeks). A new `:latest` was tagged on Friday and our pod happened to crash on Sunday - now no EFS mounts work.

**Comment by 2uasimojo** [comment]
@ossareh - are the symptoms the same as what’s in the description here, or something different?

**Comment by ossareh** [comment]
Hi there @2uasimojo, the specific issues I'm having are documented in #192 (incorrectly closed by the OP; hoping that a mod can reopen it). My prior comment on this thread is in relation to very few tagged releases resulting in issues such as accidental upgrades to core pieces of infrastructure, i.e agreeing with your statement of:

> We will use latest for the time being, but would like to be able to use a "frozen" version as soon as feasible. Thanks in advance!

**Comment by 2uasimojo** [comment]
Roger that @ossareh. I was mainly trying to nail down whether #185 was the culprit or not. Looking at the commit history, I see quite a bit of change in the past two or three months, which (IIRC -- no way to tell looking at dockerhub) was the last time `latest` was tagged.

**Comment by wongma7** [comment]
https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/202 is to push to a 7 digit sha tag upon merge to master branch. instead of to `latest` tag.

**Comment by 2uasimojo** [comment]
Thanks @wongma7 -- this ought to satisfy our needs nicely for the medium term.

**Comment by adammw** [comment]
v1.0.0 was just released, seems to fix our issue

**Comment by 2uasimojo** [comment]
Thanks all!
