### ISSUE TITLE
Watchdog errors

### ISSUE THREAD

**Issue by zachaller** [kubernetes-sigs/aws-efs-csi-driver#214]
/kind bug

**What happened?**
We needed to use access point mounts so we have been experimenting with the dev deployment but the recent changes in the last 3-4 days seems to have broken watchdog

**What you expected to happen?**

**How to reproduce it (as minimally and precisely as possible)?**

**Anything else we need to know?**:

```
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.002178       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.002182       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.044359       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.050033       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.050038       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.098262       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.104088       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
I0716 13:59:31.104313       1 reaper.go:61] Waited for child process 0
E0716 13:59:31.154611       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.159548       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.159567       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.198321       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.202916       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.202930       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.251594       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
E0716 13:59:31.256505       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.256512       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.308198       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-watchdog", line 997, in <module>
    main()
  File "/usr/bin/amazon-efs-mount-watchdog", line 977, in main
    bootstrap_logging(config)
  File "/usr/bin/amazon-efs-mount-watchdog", line 260, in bootstrap_logging
    raw_level = config.get(CONFIG_SECTION, 'logging_level')
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'mount-watchdog'
E0716 13:59:31.313564       1 efs_watch_dog.go:85] Process amazon-efs-mount-watchdog exits exit status 1
W0716 13:59:31.313582       1 reaper.go:59] Failed to wait for child process no child processes
E0716 13:59:31.358518       1 efs_watch_dog.go:131] amazon-efs-mount-watchdog[Error]: Traceback (most recent call last):
  File "/usr/bin/amazon-efs-mount-wa
```

**Environment**
- Kubernetes version (use `kubectl version`): 1.17.8
- Driver version: latest

**Comment by wongma7** [comment]
Yes, https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/212 made a breaking change to the dev overlay but the dev image still points to tag `latest` which was not/is no longer updated. 

The fix IMO is to push to tag `master` and have the dev overlay point to that: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/215

**Comment by wongma7** [comment]
@zachaller could you try the new dev overlay which references the `master` tag that was just pushed. Thanks

**Comment by zachaller** [comment]
@wongma7 looks to have fixed it thank!
