### ISSUE TITLE
POD ContainerCreating Status, Failed to Mount EFS

### ISSUE THREAD

**Issue by nelsonflorez11** [kubernetes-sigs/aws-efs-csi-driver#239]
Hello
I am trying to configure EFS in EKS with the following link aws-efs-csi-driver/examples/kubernetes/statefulset /specs/ example.yaml

I experience error when starting the POD, the pv and pvc start correctly but not the POD

```
nelson@libertad1:~/testdos$ kubectl get  pod 
NAME      READY     STATUS              RESTARTS   AGE
efs-app   0/1       ContainerCreating   0          18s
nelson@libertad1:~/testdos$ kubectl get  pv
NAME      CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                STORAGECLASS   REASON    AGE
efs-pv1   5Gi        RWX            Retain           Bound     default/efs-claim1   efs-sc                   25s
efs-pv2   5Gi        RWX            Retain           Bound     default/efs-claim2   efs-sc                   25s
nelson@libertad1:~/testdos$ kubectl get  pvc
NAME         STATUS    VOLUME    CAPACITY   ACCESS MODES   STORAGECLASS   AGE
efs-claim1   Bound     efs-pv1   5Gi        RWX            efs-sc         29s
efs-claim2   Bound     efs-pv2   5Gi        RWX            efs-sc         28s
nelson@libertad1:~/testdos$ kubectl get  pod 
NAME      READY     STATUS              RESTARTS   AGE
efs-app   0/1       ContainerCreating   0          6m56s

```

Describe mentions that you can not mount the EFS, someone else has presented this error?
```

Events:
  Type     Reason       Age                From                                     Message
  ----     ------       ----               ----                                     -------
  Normal   Scheduled    14m                default-scheduler                        Successfully assigned default/efs-app to ip-192-168-10-132.ec2.internal
  Warning  FailedMount  12m                kubelet, ip-192-168-10-132.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[efs-volume-1 efs-volume-2], unattached volumes=[default-token-dqm5l efs-volume-1 efs-volume-2]: timed out waiting for the condition
  Warning  FailedMount  12m (x3 over 14m)  kubelet, ip-192-168-10-132.ec2.internal  MountVolume.SetUp failed for volume "efs-pv1" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "fs-d57db957:/dir1" at "/var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv1/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o tls fs-d57db957:/dir1 /var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv1/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
mount.nfs4: mounting 127.0.0.1:/dir1 failed, reason given by server: No such file or directory
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
  File "/lib64/python2.7/threading.py", line 757, in run
  File "/sbin/mount.efs", line 605, in poll_tunnel_process
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
  Warning  FailedMount  10m                kubelet, ip-192-168-10-132.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[efs-volume-1 efs-volume-2], unattached volumes=[efs-volume-1 efs-volume-2 default-token-dqm5l]: timed out waiting for the condition
  Warning  FailedMount  8m (x11 over 14m)  kubelet, ip-192-168-10-132.ec2.internal  MountVolume.SetUp failed for volume "efs-pv2" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "fs-d57db957:/dir2" at "/var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv2/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o tls fs-d57db957:/dir2 /var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv2/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
mount.nfs4: mounting 127.0.0.1:/dir2 failed, reason given by server: No such file or directory
  Warning  FailedMount  8m                 kubelet, ip-192-168-10-132.ec2.internal  Unable to attach or mount volumes: unmounted volumes=[efs-volume-2 efs-volume-1], unattached volumes=[efs-volume-2 default-token-dqm5l efs-volume-1]: timed out waiting for the condition
  Warning  FailedMount  4m (x10 over 14m)  kubelet, ip-192-168-10-132.ec2.internal  MountVolume.SetUp failed for volume "efs-pv1" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = Could not mount "fs-d57db957:/dir1" at "/var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv1/mount": mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t efs -o tls fs-d57db957:/dir1 /var/lib/kubelet/pods/bd5390dd-1097-495b-8b4a-38fd6035bf6f/volumes/kubernetes.io~csi/efs-pv1/mount
Output: Could not start amazon-efs-mount-watchdog, unrecognized init system "aws-efs-csi-dri"
mount.nfs4: mounting 127.0.0.1:/dir1 failed, reason given by server: No such file or directory
nelson@libertad1:~/testdos$ 
```

The Security Groups of the cluster VPC have the correct permissions and they are assigned to the EFS in "Inbound rules"

Inbound rules
Type | Protocol | Port range | Source | Description - optional
-- | -- | -- | -- | --
NFS | TCP | 2049 | 192.168.0.0/16 | Store

**Comment by jlehtimaki** [comment]
@nelsonflorez11 I think you'r problem is *partly* because of `mount.nfs4: mounting 127.0.0.1:/dir1 failed, reason given by server: No such file or directory`.

I'm also seeing this sort of error where kubelet says it's timing out:
```
Name:         efs-app
Namespace:    default
Priority:     0
Node:         ip-10-0-4-11.eu-west-1.compute.internal/10.0.4.11
Start Time:   Fri, 14 Aug 2020 16:22:40 +0300
Labels:       <none>
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Pending
IP:           
IPs:          <none>
Containers:
  app:
    Container ID:  
    Image:         centos
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
    Args:
      -c
      while true; do echo $(date -u) >> /data/out.txt; sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from persistent-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lxtwk (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  persistent-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  drone-pvc
    ReadOnly:   false
  default-token-lxtwk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lxtwk
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                    From                                              Message
  ----     ------              ----                   ----                                              -------
  Normal   Scheduled           20m                    default-scheduler                                 Successfully assigned drone/efs-app to ip-10-0-4-11.eu-west-1.compute.internal
  Warning  FailedMount         4m26s (x6 over 17m)    kubelet, ip-10-0-4-11.eu-west-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[persistent-storage default-token-lxtwk]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m57s (x8 over 18m)    attachdetach-controller                           AttachVolume.Attach failed for volume "efs-pv" : attachment timeout for volume fs-954ee65f
  Warning  FailedMount         2m11s (x2 over 8m58s)  kubelet, ip-10-0-4-11.eu-west-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[persistent-storage], unattached volumes=[default-token-lxtwk persistent-storage]: timed out waiting for the condition

```

Mounting from the node works. I'm clueless..

**Comment by nelsonflorez11** [comment]
Hello I solved it this way:

I make the correction the error was presented on the file  aws-efs-csi-driver/examples/kubernetes/volume_path/specs/example.yaml

The reason for the error is because the path in EFS / dir1 and / dir2 did not exist, if it is mounted without path it works correctly, as shown below
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-d57db957
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv2
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  mountOptions:
    - tls
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-d57db957
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data-dir1/out.txt; sleep 5; done"]
    volumeMounts:
    - name: efs-volume-2
      mountPath: /var
  volumes:
  - name: efs-volume-2
    persistentVolumeClaim:
      claimName: efs-claim2
```
However, the function that fulfilled my need to manage the permissions of the routes separately was to create access points in the EFS

Name | Access point ID | File system ID | Path | POSIX user | Creation info | State
-- | -- | -- | -- | -- | -- | --
dir1 | fsap-08d1c47a982014f52 | fs-d57db957 | /dir1 | 1001 : 1001 | 1001 : 1001 (755) | Available
dir2 | fsap-06e99a05f3a673761 | fs-d57db957 | /dir2 | 1002 : 1002 | 1002 : 1002 (755) | Available

```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-d57db957::fsap-08d1c47a982014f52
   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv2
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-d57db957::fsap-06e99a05f3a673761
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim2
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
spec:
  containers:
  - name: app
    image: centos
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date -u) >> /data-dir1/out.txt; sleep 5; done"]
    volumeMounts:
    - name: efs-volume-1
      mountPath: /dir1
    - name: efs-volume-2
      mountPath: /dir2
  volumes:
  - name: efs-volume-1
    persistentVolumeClaim:
      claimName: efs-claim1
  - name: efs-volume-2
    persistentVolumeClaim:
      claimName: efs-claim2
```
```
nelson@libertad1:~/testdos$ kubectl get pod 
NAME      READY     STATUS    RESTARTS   AGE
efs-app   1/1       Running   0          10s
```

POD successfully uploads and mounts the EFS routes **/dir1** and **/dir2**
```
nelson@libertad1:~/testdos$ kubectl exec --stdin --tty  efs-app -- /bin/bash
[root@efs-app /]# ls
bin  dev  dir1  dir2  etc  home  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
```

NOTE: Works with the latest version of the driver
```
nelson@libertad1:~/testdos$ helm list
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
aws-efs-csi-driver      default         1               2020-08-18 22:25:25.506967996 -0500 -05 deployed        aws-efs-csi-driver-0.1.0        1.0.0 
```

**Comment by jlehtimaki** [comment]
@nelsonflorez11 yup that works! Can you please close this issue!

**Comment by jurgenweber** [comment]
so is 'mountpath' deprecated then? I would expect it to work....... does it mean i need to create the path first before I can mount it? 

can it not create it when not found?
