### ISSUE TITLE
Configuring `efs-plugin` with a little resources causes the efs-controller Pod to CrashLoopBackOff

### ISSUE THREAD

**Issue by alexrocco** [kubernetes-sigs/aws-efs-csi-driver#617]
/kind bug

**What happened?**
When configuring the Helm chart with a little resource for the `efs-plugin` causes the `efs-csi-controller` Pods to CrashLoopBackOff, when there is a new PVC deployed. The PVC stays pending and no PV is created.

**What you expected to happen?**

To not CrashLoopBackOff and the PV to be created.

**How to reproduce it (as minimally and precisely as possible)?**

Just deploy the Helm chart with resource request/limit (value `controller.resources), CPU 100m, and memory 64Mi.

**Anything else we need to know?**:

The efs-csi-controller does not get OOM killed, it just becomes unhealthy and the probes start to restart the `efs-plugin` container.
`Liveness probe failed: HTTP probe failed with statuscode: 500

And it only starts to restart after the PVC is deployed.

**Environment**
- Kubernetes version (use `kubectl version`): EKS 1.20.7
- Driver version: 1.3.5

**Comment by alexrocco** [comment]
`csi-provisioner` log
```
W0119 10:04:34.492734       1 feature_gate.go:235] Setting GA feature gate Topology=true. It will be removed in a future release.
I0119 10:04:34.493103       1 feature_gate.go:243] feature gates: &{map[Topology:true]}
I0119 10:04:34.493209       1 csi-provisioner.go:132] Version: v2.1.1-0-g353098c90
I0119 10:04:34.493309       1 csi-provisioner.go:155] Building kube configs for running in cluster...
I0119 10:04:34.504826       1 connection.go:153] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0119 10:04:34.594518       1 common.go:111] Probing CSI driver for readiness
I0119 10:04:34.603628       1 csi-provisioner.go:202] Detected CSI driver efs.csi.aws.com
I0119 10:04:34.606742       1 csi-provisioner.go:244] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0119 10:04:34.607786       1 controller.go:756] Using saving PVs to API server in background
I0119 10:04:34.613453       1 leaderelection.go:243] attempting to acquire leader lease kube-system/efs-csi-aws-com...
I0119 10:04:54.338231       1 leaderelection.go:253] successfully acquired lease kube-system/efs-csi-aws-com
I0119 10:04:54.338402       1 leader_election.go:205] became leader, starting
I0119 10:04:54.339034       1 reflector.go:219] Starting reflector *v1.StorageClass (1h0m0s) from k8s.io/client-go/informers/factory.go:134
I0119 10:04:54.339405       1 reflector.go:219] Starting reflector *v1.PersistentVolumeClaim (15m0s) from k8s.io/client-go/informers/factory.go:134
I0119 10:04:54.438563       1 controller.go:835] Starting provisioner controller efs.csi.aws.com_ip-00-00-00-00.eu-central-1.compute.internal_b65e2552-71ba-48af-8f97-aaaaaa!
I0119 10:04:54.438618       1 volume_store.go:97] Starting save volume queue
I0119 10:04:54.438799       1 reflector.go:219] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872
I0119 10:04:54.438856       1 reflector.go:219] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:869
I0119 10:04:54.539142       1 controller.go:884] Started provisioner controller efs.csi.aws.com_ip-00-00-00-00.eu-central-1.compute.internal_b65e2552-71ba-48af-8f97-aaaaa!
I0119 10:04:54.539158       1 controller.go:1332] provision "default/kubernetes-test-test-pvc" class "kubernetes-test": started
I0119 10:04:54.541631       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"kubernetes-test-test-pvc", UID:"c1947561-ce02-4174-9b32-aaa", APIVersion:"v1", ResourceVersion:"45277775", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/kubernetes-test-test-pvc"
I0119 10:05:00.990621       1 controller.go:1106] Temporary error received, adding PVC c1947561-ce02-4174-9b32-aaa to claims in progress
W0119 10:05:00.990643       1 controller.go:958] Retrying syncing claim "c1947561-ce02-4174-9b32-aaa", failure 0
E0119 10:05:00.990667       1 controller.go:981] error syncing claim "c1947561-ce02-4174-9b32-aa": failed to provision volume with StorageClass "kubernetes-test": rpc error: code = Unavailable desc = transport is closing
E0119 10:05:00.990627       1 connection.go:131] Lost connection to unix:///var/lib/csi/sockets/pluginproxy/csi.sock.
F0119 10:05:00.990735       1 connection.go:87] Lost connection to CSI driver, exiting
goroutine 33 [running]:
k8s.io/klog/v2.stacks(0xc0000b0001, 0xc0004dc1a0, 0x57, 0xc4)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:1026 +0xb9
k8s.io/klog/v2.(*loggingT).output(0x2633420, 0xc000000003, 0x0, 0x0, 0xc0003f0310, 0x256268e, 0xd, 0x57, 0x0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:975 +0x19b
k8s.io/klog/v2.(*loggingT).printf(0x2633420, 0x3, 0x0, 0x0, 0x0, 0x0, 0x19b2b4b, 0x26, 0x0, 0x0, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:750 +0x191
k8s.io/klog/v2.Fatalf(...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:1514
github.com/kubernetes-csi/csi-lib-utils/connection.ExitOnConnectionLoss.func1(0x2633420)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go:87 +0x1eb
github.com/kubernetes-csi/csi-lib-utils/connection.connect.func1(0xc0002d09f0, 0x29, 0x4a816e4cd, 0x4a816e4cd, 0xc0000f9101, 0x10, 0xc0006544e0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go:134 +0x2aa
google.golang.org/grpc.WithDialer.func1(0x1bb23c0, 0xc000351860, 0xc0002d09f0, 0x29, 0x10, 0x17e2380, 0xa06603f6adfd5cf, 0x26647c0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/dialoptions.go:398 +0x8e
google.golang.org/grpc/internal/transport.dial(0x1bb23c0, 0xc000351860, 0xc00019a530, 0xc0002d09f0, 0x29, 0x198d2db, 0x9, 0xc0002e96d8, 0x0, 0x0, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/http2_client.go:143 +0x2dd
google.golang.org/grpc/internal/transport.newHTTP2Client(0x1bb23c0, 0xc000351860, 0x1bb2340, 0xc000656540, 0xc0002d09f0, 0x29, 0x198d2db, 0x9, 0xc0002e96d8, 0x0, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/http2_client.go:183 +0x15e
google.golang.org/grpc/internal/transport.NewClientTransport(...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/transport.go:579
google.golang.org/grpc.(*addrConn).createTransport(0xc0000de000, 0xc0002d09f0, 0x29, 0x198d2db, 0x9, 0xc0002e96d8, 0x0, 0x0, 0x0, 0x1992c66, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1322 +0x40f
google.golang.org/grpc.(*addrConn).tryAllAddrs(0xc0000de000, 0xc00041fc40, 0x1, 0x1, 0xc07216783b0acea5, 0xadd6ca9b7, 0x2633100, 0x1bcb020, 0xc0003ec540, 0x0, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1252 +0x38d
google.golang.org/grpc.(*addrConn).resetTransport(0xc0000de000)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1167 +0x265
created by google.golang.org/grpc.(*addrConn).connect
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:843 +0x12a

goroutine 1 [select]:
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00058f5e8, 0x1b73ac0, 0xc0001339b0, 0xc0002e1301, 0xc000088360)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:167 +0x149
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0002df5e8, 0x12a05f200, 0x0, 0xc0002e1301, 0xc000088360)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90
k8s.io/client-go/tools/leaderelection.(*LeaderElector).renew(0xc000430240, 0x1bb2340, 0xc0002e13c0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:263 +0x107
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0xc000430240, 0x1bb2340, 0xc0002e1380)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:208 +0x13b
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1bb2380, 0xc00009e000, 0x1bbc6a0, 0xc0001d17c0, 0x37e11d600, 0x2540be400, 0x12a05f200, 0xc0005645b0, 0x1a45bf0, 0x1a45bf8, ...)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:222 +0x9c
github.com/kubernetes-csi/csi-lib-utils/leaderelection.(*leaderElection).Run(0xc000574090, 0xc000574090, 0x0)
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go:222 +0x57f
main.main()
	/home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/cmd/csi-provisioner/csi-provisioner.go:490 +0x2d7a
```

PVC event
```
  Warning  ProvisioningFailed    52s                   efs.csi.aws.com_ip-00-00-00-00.eu-central-1.compute.internal_9f88d78d-5a05-4e7b-9623-aaaa   failed to provision volume with StorageClass "kubernetes-test": rpc error: code = Unavailable desc = transport is closing

```

**Comment by alexrocco** [comment]
Changing the memory 128Mi fixes the issue, but still weird as no OOM killed event happened.
