### ISSUE TITLE
efs-plugin - panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by usrbinsam** [kubernetes-sigs/aws-efs-csi-driver#705]
/kind bug

**What happened?**

When launching a pod with dynamic provisioning, the controller goes into CrashLoopBackOff. 

**What you expected to happen?**

PVC to become ready, Pod to become ready, and no CrashLoopBackOff.

**How to reproduce it (as minimally and precisely as possible)?**

Using the PVC & Pod from the example:

```
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-test-claim
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cluster01-efs-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  namespace: storage
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-test-claim
```

**Anything else we need to know?**:

Deploying to an `m6g.medium` instance.

### `efs-plugin` log:
```
I0608 00:44:26.630799       1 config_dir.go:62] Mounted directories do not exist, creating directory at '/etc/amazon/efs'
I0608 00:44:26.638282       1 driver.go:140] Did not find any input tags.
I0608 00:44:26.638402       1 driver.go:113] Registering Node Server
I0608 00:44:26.638412       1 driver.go:115] Registering Controller Server
I0608 00:44:26.638423       1 driver.go:118] Starting efs-utils watchdog
I0608 00:44:26.638480       1 efs_watch_dog.go:215] Copying /etc/amazon/efs/efs-utils.conf since it doesn't exist
I0608 00:44:26.638539       1 efs_watch_dog.go:215] Copying /etc/amazon/efs/efs-utils.crt since it doesn't exist
I0608 00:44:26.640005       1 driver.go:124] Starting reaper
I0608 00:44:26.640013       1 driver.go:127] Listening for connections on address: &net.UnixAddr{Name:"/var/lib/csi/sockets/pluginproxy/csi.sock", Net:"unix"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x684a2c]

goroutine 45 [running]:
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*IntHeap).Push(...)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:25
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*GidAllocator).releaseGid(0x4000092c98, {0x400003aa98, 0x14}, 0x3e1)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/gid_allocator.go:74 +0xec
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).CreateVolume(0x4000092c00, {0x9c3720, 0x4000401ef0}, 0x4000410230)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/controller.go:244 +0x1008
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler.func1({0x9c3720, 0x4000401ef0}, {0x7b8960, 0x4000410230})
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5676 +0x7c
github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver.(*Driver).Run.func1({0x9c3720, 0x4000401ef0}, {0x7b8960, 0x4000410230}, 0x4000308e20, 0x40004050b0)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/pkg/driver/driver.go:101 +0x48
github.com/container-storage-interface/spec/lib/go/csi._Controller_CreateVolume_Handler({0x7c88e0, 0x4000092c00}, {0x9c3720, 0x4000401ef0}, 0x400040e900, 0x81f008)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go:5678 +0x14c
google.golang.org/grpc.(*Server).processUnaryRPC(0x40000bfc00, {0x9cd720, 0x40000c1380}, 0x40003f46c0, 0x40002e1fb0, 0xe760c0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1286 +0xc14
google.golang.org/grpc.(*Server).handleStream(0x40000bfc00, {0x9cd720, 0x40000c1380}, 0x40003f46c0, 0x0)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:1609 +0xa54
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x400030c290, 0x40000bfc00, {0x9cd720, 0x40000c1380}, 0x40003f46c0)
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:934 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/kubernetes-sigs/aws-efs-csi-driver/vendor/google.golang.org/grpc/server.go:932 +0x1f0
```

### `csi-provisioner` log:

```
W0608 00:47:36.761905       1 feature_gate.go:235] Setting GA feature gate Topology=true. It will be removed in a future release.
I0608 00:47:36.767849       1 feature_gate.go:243] feature gates: &{map[Topology:true]}
I0608 00:47:36.767977       1 csi-provisioner.go:132] Version: v2.1.1-0-g353098c90
I0608 00:47:36.768057       1 csi-provisioner.go:155] Building kube configs for running in cluster...
I0608 00:47:36.798541       1 connection.go:153] Connecting to unix:///var/lib/csi/sockets/pluginproxy/csi.sock
I0608 00:47:36.799264       1 common.go:111] Probing CSI driver for readiness
I0608 00:47:36.800916       1 csi-provisioner.go:202] Detected CSI driver efs.csi.aws.com
I0608 00:47:36.801972       1 csi-provisioner.go:244] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I0608 00:47:36.802452       1 controller.go:756] Using saving PVs to API server in background
I0608 00:47:36.803290       1 leaderelection.go:243] attempting to acquire leader lease storage/efs-csi-aws-com...
I0608 00:48:11.669446       1 leaderelection.go:253] successfully acquired lease storage/efs-csi-aws-com
I0608 00:48:11.669560       1 leader_election.go:205] became leader, starting
I0608 00:48:11.670215       1 reflector.go:219] Starting reflector *v1.StorageClass (1h0m0s) from k8s.io/client-go/informers/factory.go:134
I0608 00:48:11.671317       1 reflector.go:219] Starting reflector *v1.PersistentVolumeClaim (15m0s) from k8s.io/client-go/informers/factory.go:134
I0608 00:48:11.769691       1 controller.go:835] Starting provisioner controller efs.csi.aws.com_ip-192-168-86-150.us-west-2.compute.internal_c89cdae7-7953-4e44-8df6-ac0510aec0c5!
I0608 00:48:11.769758       1 volume_store.go:97] Starting save volume queue
I0608 00:48:11.769945       1 reflector.go:219] Starting reflector *v1.PersistentVolume (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:869
I0608 00:48:11.770270       1 reflector.go:219] Starting reflector *v1.StorageClass (15m0s) from sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller/controller.go:872
I0608 00:48:11.870093       1 controller.go:884] Started provisioner controller efs.csi.aws.com_ip-192-168-86-150.us-west-2.compute.internal_c89cdae7-7953-4e44-8df6-ac0510aec0c5!
I0608 00:48:11.870326       1 controller.go:1332] provision "storage/efs-test-claim" class "cluster01-efs-sc": started
I0608 00:48:11.873143       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"storage", Name:"efs-test-claim", UID:"5c82d082-f63a-40de-9b5c-ebd85d9f2921", APIVersion:"v1", ResourceVersion:"2818800", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "storage/efs-test-claim"
I0608 00:48:12.003980       1 controller.go:1106] Temporary error received, adding PVC 5c82d082-f63a-40de-9b5c-ebd85d9f2921 to claims in progress
W0608 00:48:12.004108       1 controller.go:958] Retrying syncing claim "5c82d082-f63a-40de-9b5c-ebd85d9f2921", failure 0
E0608 00:48:12.004184       1 controller.go:981] error syncing claim "5c82d082-f63a-40de-9b5c-ebd85d9f2921": failed to provision volume with StorageClass "cluster01-efs-sc": rpc error: code = Unavailable desc = transport is closing
E0608 00:48:12.004319       1 connection.go:131] Lost connection to unix:///var/lib/csi/sockets/pluginproxy/csi.sock.
F0608 00:48:12.004433       1 connection.go:87] Lost connection to CSI driver, exiting
goroutine 22 [running]:
k8s.io/klog/v2.stacks(0x400000e001, 0x40003ca000, 0x57, 0x274)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:1026 +0xac
k8s.io/klog/v2.(*loggingT).output(0x1f9ff80, 0x4000000003, 0x0, 0x0, 0x4000131490, 0x1ec23f2, 0xd, 0x57, 0x0)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:975 +0x168
k8s.io/klog/v2.(*loggingT).printf(0x1f9ff80, 0x3, 0x0, 0x0, 0x0, 0x0, 0x1309a71, 0x26, 0x0, 0x0, ...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:750 +0x12c
k8s.io/klog/v2.Fatalf(...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/k8s.io/klog/v2/klog.go:1514
github.com/kubernetes-csi/csi-lib-utils/connection.ExitOnConnectionLoss.func1(0x1f9ff80)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go:87 +0x1d0
github.com/kubernetes-csi/csi-lib-utils/connection.connect.func1(0x40003f48d0, 0x29, 0x4a8171245, 0x4a8171245, 0x40003f7d01, 0x37, 0x400006b0f8)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/github.com/kubernetes-csi/csi-lib-utils/connection/connection.go:134 +0x23c
google.golang.org/grpc.WithDialer.func1(0x1508340, 0x40002e8000, 0x40003f48d0, 0x29, 0x422ba000bf5b6e00, 0x117d400, 0x400049d900, 0xffff94b9dc08)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/dialoptions.go:398 +0x80
google.golang.org/grpc/internal/transport.dial(0x1508340, 0x40002e8000, 0x4000010d70, 0x40003f48d0, 0x29, 0x12e4205, 0x9, 0x40003fa0a8, 0x0, 0x0, ...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/http2_client.go:143 +0x210
google.golang.org/grpc/internal/transport.newHTTP2Client(0x1508340, 0x40002e8000, 0x15082c0, 0x40004e9b80, 0x40003f48d0, 0x29, 0x12e4205, 0x9, 0x40003fa0a8, 0x0, ...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/http2_client.go:183 +0xe0
google.golang.org/grpc/internal/transport.NewClientTransport(...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/internal/transport/transport.go:579
google.golang.org/grpc.(*addrConn).createTransport(0x40000c0dc0, 0x40003f48d0, 0x29, 0x12e4205, 0x9, 0x40003fa0a8, 0x0, 0x0, 0x0, 0x12e9bed, ...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1322 +0x300
google.golang.org/grpc.(*addrConn).tryAllAddrs(0x40000c0dc0, 0x400049d9c0, 0x1, 0x1, 0xc0a01a5800411f8c, 0xcde19bccf, 0x1f9fc60, 0x15211a0, 0x40003c0380, 0x0, ...)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1252 +0x2d0
google.golang.org/grpc.(*addrConn).resetTransport(0x40000c0dc0)
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:1167 +0x1b8
created by google.golang.org/grpc.(*addrConn).connect
        /home/prow/go/src/github.com/aws/eks-distro/projects/kubernetes-csi/external-provisioner/external-provisioner/vendor/google.golang.org/grpc/clientconn.go:843 +0x1a8
```

### `kubectl describe sc cluster01-efs-sc`

```Name:                  cluster01-efs-sc
IsDefaultClass:        No
Annotations:           meta.helm.sh/release-name=aws-efs-csi-driver,meta.helm.sh/release-namespace=storage
Provisioner:           efs.csi.aws.com
Parameters:            basePath=/students,fileSystemId=fs-09d360891310a6388,gid=993,provisioningMode=efs-ap,uid=995
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

**Environment**
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.6-eks-7d68063", GitCommit:"f24e667e49fb137336f7b064dba897beed639bad", GitTreeState:"clean", BuildDate:"2022-02-23T19:32:14Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.9-eks-a64ea69", GitCommit:"540410f9a2e24b7a2a870ebfacb3212744b5f878", GitTreeState:"clean", BuildDate:"2022-05-12T19:15:31Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Driver version: `amazon/aws-efs-csi-driver:v1.3.8`

**Comment by usrbinsam** [comment]
Appears to be a duplicate of #693
